apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::559395821090:role/eksctl-spot-cluster-nodegroup-spo-NodeInstanceRole-WS6XXTX3BSKM
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::559395821090:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-22T08:15:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1469"
  uid: c0b880b2-737a-4271-a48f-61f87f87c1d4
